replacing with internal repo

diff --git a/deploy-sentinel/teletraan/RESTARTING b/deploy-sentinel/teletraan/RESTARTING
--- a/deploy-sentinel/teletraan/RESTARTING
+++ b/deploy-sentinel/teletraan/RESTARTING
@@ -1,12 +1,14 @@
 #!/bin/bash
 
+# RESTARTING is the script to start or restart service.
+
+echo "This is RESTARTING!"
+
 set -e
+set -x
+#simulate failure
+#echo "yes"
+#sleep 300
+#exit 100
 
-echo Running RESTARTING script.
-
-# Register knox keys
-knox register -g -k teletraan:prod:rodimusapitoken
-knox register -g -k teletraan:integ:rodimusapitoken
-
-# Start service
-python ../mysite/manage.py runserver 0.0.0.0:8000 &
+configure-serviceset -c teletraan/config/serviceset.conf
diff --git a/deploy-sentinel/teletraan/STOPPING b/deploy-sentinel/teletraan/STOPPING
--- a/deploy-sentinel/teletraan/STOPPING
+++ b/deploy-sentinel/teletraan/STOPPING
@@ -1,5 +1,7 @@
 #!/bin/bash
 
-echo Running STOPPING script.
+set -e
 
-sleep 10m # Waits 10 minutes.
+echo "STOPPING"
+#echo "Simulate failure"
+#exit 100
